# Generated by Django 6.0.3 on 2026-03-24 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_names', models.CharField(max_length=150, verbose_name='Nombres')),
                ('paternal_last_name', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('maternal_last_name', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('document_type', models.CharField(choices=[('DNI', 'DNI - Documento Nacional de Identidad'), ('RUC', 'RUC - Registro Único de Contribuyentes'), ('CE', 'Carnet de Extranjería'), ('PAS', 'Pasaporte')], default='DNI', max_length=3, verbose_name='Tipo de Documento')),
                ('document_number', models.CharField(max_length=15, unique=True, verbose_name='Número de Documento')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Teléfono/Celular')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
            },
        ),
    ]
