# Generated by Django 6.0.3 on 2026-03-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='document_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Número de Documento'),
        ),
    ]
