# Generated by Django 6.0.3 on 2026-03-24 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customer_document_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color_hex', models.CharField(default='#6c757d', help_text='Código hexadecimal para la UI (ej: #444444)', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=255, verbose_name='Dirección (Av/Calle/Jr)')),
                ('address_line_2', models.CharField(blank=True, max_length=255, verbose_name='Dpto/Int/Urb (Opcional)')),
                ('reference', models.TextField(blank=True, verbose_name='Referencia')),
                ('district', models.CharField(max_length=100, verbose_name='Distrito')),
                ('province', models.CharField(max_length=100, verbose_name='Provincia')),
                ('state', models.CharField(max_length=100, verbose_name='Departamento')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Código Postal')),
                ('is_default', models.BooleanField(default=False, verbose_name='Dirección Principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.customer')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.role'),
        ),
    ]
